[sfu]
ballast = 0
withstats = false

[router]
maxbandwidth = 1500
maxpackettrack = 500
audiolevelthreshold = 40
audiolevelinterval = 1000
audiolevelfilter = 20

[router.simulcast]
bestqualityfirst = true
enabletemporallayer = false

[webrtc]
portrange = [5000, 5200]
sdpsemantics = "unified-plan"
mdns = true

[webrtc.candidates]

[webrtc.timeouts]
disconnected = 5
failed = 25
keepalive = 2

[[webrtc.iceserver]]
urls = ["stun:coturn:3478"]

[[webrtc.iceserver]]
urls = ["turn:coturn:3478"]
username = "ember"
credential = "${TURN_SECRET}"

[turn]
enabled = false
realm = "ion"
address = "0.0.0.0:3478"

[turn.auth]
credentials = "pion=ion"

[log]
v = 1
